# Generated by Django 4.0.4 on 2022-06-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
