# Generated by Django 4.0.4 on 2022-05-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_profile_profile_pic'),
        ('Blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], null=True)),
                ('bloodgroup', models.IntegerField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')])),
                ('unit', models.PositiveIntegerField(default=0)),
                ('Requisition_form', models.ImageField(default='blood-sample.jpg', upload_to='requistion_forms/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('request_by_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
    ]
