# Generated by Django 4.0.4 on 2022-05-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0004_bloodrequest_email_bloodrequest_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='patient_bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
    ]
