# Generated by Django 4.0.4 on 2022-06-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blood', '0005_alter_bloodrequest_patient_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
