# Generated by Django 4.0.4 on 2022-06-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_profile_profile_pic'),
        ('Blood', '0006_alter_bloodrequest_request_by_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
