# Generated by Django 4.0.4 on 2022-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0010_bloodrequest_response_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='response_date',
            field=models.DateTimeField(auto_now=True, max_length=30),
        ),
    ]
