# Generated by Django 4.0.4 on 2022-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0012_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='appointmentid',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
