# Generated by Django 4.0.4 on 2022-06-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0013_donationrequest_appointmentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='appointmentid',
            new_name='campaignid',
        ),
    ]
