# Generated by Django 4.0.4 on 2022-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0014_rename_appointmentid_donationrequest_campaignid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='request_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='campaignid',
            field=models.IntegerField(default=0),
        ),
    ]
