# Generated by Django 4.0.4 on 2022-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0017_donationrequest_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='response_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='response_message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
