# Generated by Django 4.0.4 on 2022-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0019_rename_request_by_donor_donationrequest_request_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
