# Generated by Django 4.0.4 on 2022-06-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0020_donationrequest_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='Requisition_form',
            new_name='MR',
        ),
    ]
