# Generated by Django 4.0.4 on 2022-06-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0021_rename_requisition_form_bloodrequest_mr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='MR',
            new_name='medical_report',
        ),
    ]
