# Generated by Django 4.0.4 on 2022-08-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0022_rename_mr_bloodrequest_medical_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='disease',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='medical_report',
            field=models.ImageField(default='medical-report.png', upload_to='medical_report/'),
        ),
    ]
